set(Plugin-Name "Awesome Example Application")
set(Plugin-Version "0.1")
set(Plugin-Vendor "Awesome Company")
set(Plugin-ContactAddress "http://www.awesomeproject.my")
set(Require-Plugin org.mitk.core.ext org.mitk.gui.qt.common org.mitk.gui.qt.datamanager org.mitk.gui.qt.ext)
