set(Plugin-Name "KMaps Application")
set(Plugin-Version "0.1")
set(Plugin-Vendor "University of Turin")
set(Plugin-ContactAddress "http://kmaps.unito.it")
set(Require-Plugin org.mitk.core.ext org.mitk.gui.qt.common org.mitk.gui.qt.datamanager org.mitk.gui.qt.ext)
