name: 'Commit Message Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
    - name: Check for issue
        uses: gsactions/commit-message-checker@v1
        with:
          pattern: 'issue-[0-9]:+$'
          error: 'You need at least one "issue-<issue number>:" line.'
